version: '3.9'

volumes:
  lightyDev: {}

services:
  db:
    image: postgres
    restart: always
    shm_size: 128mb
    ports:
      - 5300:5432
    volumes:
      - lightyDev:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: lighty
