export const notificationTypes = {
  GATHERING_INVITATION_RECEIVED: 'GATHERING_INVITATION_RECEIVED',
  GATHERING_INVITATION_ACCEPTED: 'GATHERING_INVITATION_ACCEPTED',
  GROUP_INVITATION: 'GROUP_INVITATION',
  FRIEND_REQUEST: 'FRIEND_REQUEST',
  FRIEND_REQUEST_ACCEPTED: 'FRIEND_REQUEST_ACCEPTED',
  FEED_COMMENT: 'FEED_COMMENT',
  FEED_COMMENT_MENTIONED: 'FEED_COMMENT_MENTIONED',
  FRIEND_FEED_WRITEN: 'FRIEND_FEED_WRITEN',
  GATHERING_FEED_WRITEN: 'GATHERING_FEED_WRITEN',
};

export type NotificationTypes = keyof typeof notificationTypes;
