name: Test

on:
  push:
    branches: ['develop']

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1

      - name: Append Environment Variables File
        run: |
          echo "${{ secrets.ENV_TEST }}" > .env.test

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'npm'

      - name: Run Test
        env:
          DATABASE_URL: ${{ secrets.TEST_DATABASE_URL }}
        run: |
          npm install
          npm run docker:up
          npm run test
          npm run test:unit
